# BASES DE DATOS
# Práctica 1: Liga de fútbol
# Fichero: Makefile
# Autores:  Álvaro Seral Gracia                 816456  816456@unizar.es
#           Cristian Andrei Selivanov Dobrisan  819425  819425@unizar.es
#           Dorian Boleslaw Wozniak             817570  817570@unizar.es
# Resumen: Compila obtenerNombresCortos.cpp
#
# Entregado el 4 de abril de 2022

all: obtenerNombresCortos

obtenerNombresCortos: obtenerNombresCortos.cpp
	g++ obtenerNombresCortos.cpp -o obtenerNombresCortos
