/* Generated By:JavaCC: Do not edit this line. clikeConstants.java */
package traductor;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface clikeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int tBOOL = 3;
  /** RegularExpression Id. */
  int tCHAR = 4;
  /** RegularExpression Id. */
  int tINT = 5;
  /** RegularExpression Id. */
  int tVOID = 6;
  /** RegularExpression Id. */
  int tIF = 7;
  /** RegularExpression Id. */
  int tELSE = 8;
  /** RegularExpression Id. */
  int tWHILE = 9;
  /** RegularExpression Id. */
  int tRETURN = 10;
  /** RegularExpression Id. */
  int tPAREN_INI = 11;
  /** RegularExpression Id. */
  int tPAREN_FIN = 12;
  /** RegularExpression Id. */
  int tLLAVE_INI = 13;
  /** RegularExpression Id. */
  int tLLAVE_FIN = 14;
  /** RegularExpression Id. */
  int tCOMA = 15;
  /** RegularExpression Id. */
  int tPUNTO_COMA = 16;
  /** RegularExpression Id. */
  int tASIGNAR = 17;
  /** RegularExpression Id. */
  int tSUMA = 18;
  /** RegularExpression Id. */
  int tRESTA = 19;
  /** RegularExpression Id. */
  int tMULTI = 20;
  /** RegularExpression Id. */
  int tDIV = 21;
  /** RegularExpression Id. */
  int tMODULO = 22;
  /** RegularExpression Id. */
  int tMAYOR = 23;
  /** RegularExpression Id. */
  int tMENOR = 24;
  /** RegularExpression Id. */
  int tMAYOR_IGUAL = 25;
  /** RegularExpression Id. */
  int tMENOR_IGUAL = 26;
  /** RegularExpression Id. */
  int tIGUAL = 27;
  /** RegularExpression Id. */
  int tDISTINTO = 28;
  /** RegularExpression Id. */
  int tCORCH_INI = 29;
  /** RegularExpression Id. */
  int tCORCH_FIN = 30;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 31;
  /** RegularExpression Id. */
  int tCOMENTARIO = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LETTER>",
    "<DIGIT>",
    "\"bool\"",
    "\"char\"",
    "\"int\"",
    "\"void\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"<>\"",
    "\"[\"",
    "\"]\"",
    "<tIDENTIFICADOR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<tCOMENTARIO>",
  };

}
