/*
-- Query: select distinct model nombreM',' manufacturer clvFabricante',' engine_type Motor from planes where model<>""
-- Date: 2022-05-22 18:48
*/
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('EMB-145XR','EMBRAER','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A320-214','AIRBUS INDUSTRIE','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3TO','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('747-422','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('EMB-145LR','EMBRAER','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('747-451','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-824','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('EMB-135LR','EMBRAER','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-524','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-332','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-224','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-76N','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('EMB-145EP','EMBRAER','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DC-9-31','DOUGLAS','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DC-9-31','MCDONNELL DOUGLAS','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-724','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('EMB-135ER','EMBRAER','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-3P6','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3G7','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('CL-600-2B19','CANADAIR','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A321-211','AIRBUS INDUSTRIE','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-33A','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-7BD','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('CL-600-2B19','BOMBARDIER INC','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('ERJ 190-100 IGW','EMBRAER','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A321-211','AIRBUS','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-2B7','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-7H4','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('150','CESSNA','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A320-214','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('421C','CESSNA','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-322','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-23N','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('777-222','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DC-9-82(MD-82)','MCDONNELL DOUGLAS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('SAAB 340B','SAAB-SCANIA','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('EMB-120ER','EMBRAER','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('EMB-120','EMBRAER','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-201','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-2B7','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('777-224','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A330-323','AIRBUS INDUSTRIE','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-705','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('65-A90','BEECH','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('EMB-145','EMBRAER','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('T337G','CESSNA','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3H4','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A319-114','AIRBUS INDUSTRIE','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A320-211','AIRBUS INDUSTRIE','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-990','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-924','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3Y0','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3S3','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('CL-600-2C10','BOMBARDIER INC','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3Q8','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-223','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DC-9-32','DOUGLAS','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3B7','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A320-212','AIRBUS INDUSTRIE','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A319-114','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3K2','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('S-76A','SIKORSKY','Turbo-Shaft');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('G-IV','GULFSTREAM AEROSPACE','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('AS 355F1','AEROSPATIALE','Turbo-Shaft');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('PA-31-350','PIPER','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-323','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A109E','AGUSTA SPA','Turbo-Shaft');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-832','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-924ER','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('182A','CESSNA','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('690A','AERO COMMANDER','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A320-212','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('PA-32RT-300','PIPER','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('FALCON XP','PAIR MIKE E','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A320-211','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('172E','CESSNA','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DC-7BF','DOUGLAS','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('1121','AERO COMMANDER','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('E-90','BEECH','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A-1B','AVIAT AIRCRAFT INC','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-324','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('S-50A','RAVEN','None');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DC-9-51','MCDONNELL DOUGLAS','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A320-232','AIRBUS INDUSTRIE','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('S55A','RAVEN','None');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-401','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('PA-28-180','PIPER','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-4B7','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DC-9-83(MD-83)','MCDONNELL DOUGLAS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DHC-8-202','DEHAVILLAND','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('182P','CESSNA','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('172M','CESSNA','4 Cycle');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('717-200','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A320-232','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-5H4','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-222','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-251','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('FALCON-XP','WOBIG WAYNE R','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('206B','BELL','Turbo-Shaft');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('FALCON-XP','FREDERICK CHRIS K','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('T210N','CESSNA','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('550','CESSNA','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('60','BEECH','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('CL600-2D24','BOMBARDIER INC','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('C90','BEECH','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('VANS AIRCRAFT RV6','FRIEDEMANN JON','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('PA-32R-300','PIPER','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-890','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('FALCON XP','STINNETT RON','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-8FH','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('HST-550','HELIO','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-76Q','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('FALCON XP','LEBLANC GLENN T','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('KITFOX IV','MARZ BARRY','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('OTTER DHC-3','DEHAVILLAND','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-324','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-301','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('210-5(205)','CESSNA','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-33N','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-33A','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-351','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-3G5','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-3CB','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-424ER','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-232','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DC-9-32','MCDONNELL DOUGLAS','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-790','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-223','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('F85P-1','MORSE GEORGE JR','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A320-231','AIRBUS INDUSTRIE','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('ATR-72-212','AEROSPATIALE/ALENIA','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('ATR 72-212','AEROSPATIALE','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('FALCON-XP','BAUMAN RANDY','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-322','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3L9','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-317','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3T5','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-3A4','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-224','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DA 20-A1','DIAMOND AIRCRAFT IND INC','4 Cycle');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A319-112','AIRBUS INDUSTRIE','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('777-232LR','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-2Q8','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-490','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-231','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('747-2B5F','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-73A','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-212','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DC-9-41','DOUGLAS','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-7Q8','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DC-9-41','MCDONNELL DOUGLAS','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-4Q8','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-4S3','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-7AD','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('EMB-135KL','EMBRAER','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A319-132','AIRBUS INDUSTRIE','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A318-111','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A330-323','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A319-131','AIRBUS INDUSTRIE','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('DHC-8-102','BOEING OF CANADA LTD','Turbo-Prop');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-2Y5','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-230','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-282','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('767-432ER','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-282C','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-236','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A319-132','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-2P6','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-2X6C','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A319-131','AIRBUS','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A330-223','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('777-232','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('MD-88','MCDONNELL DOUGLAS CORPORATION','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-26D','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-2S7','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('MD-90-30','MCDONNELL DOUGLAS','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A319-111','AIRBUS INDUSTRIE','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('737-522','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('MD-88','MCDONNELL DOUGLAS AIRCRAFT CO','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('EXEC 162F','COBB INTL/DBA ROTORWAY INTL IN','4 Cycle');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A319-111','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('A319-112','AIRBUS','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-2G7','BOEING','Turbo-Jet');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('757-225','BOEING','Turbo-Fan');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('11AC','AERONCA','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('M-5-235C','MAULE','Reciprocating');
INSERT INTO Modelo (nombreM,clvFabricante,Motor) VALUES ('MD 83','MCDONNELL DOUGLAS AIRCRAFT CO','Turbo-Jet');
