/*
-- Query: select distinct manufacturer NombreF from planes where manufacturer<>""
-- Date: 2022-05-22 18:48
*/
INSERT INTO Fabricante (NombreF) VALUES ('EMBRAER');
INSERT INTO Fabricante (NombreF) VALUES ('AIRBUS INDUSTRIE');
INSERT INTO Fabricante (NombreF) VALUES ('BOEING');
INSERT INTO Fabricante (NombreF) VALUES ('DOUGLAS');
INSERT INTO Fabricante (NombreF) VALUES ('MCDONNELL DOUGLAS');
INSERT INTO Fabricante (NombreF) VALUES ('CANADAIR');
INSERT INTO Fabricante (NombreF) VALUES ('BOMBARDIER INC');
INSERT INTO Fabricante (NombreF) VALUES ('AIRBUS');
INSERT INTO Fabricante (NombreF) VALUES ('CESSNA');
INSERT INTO Fabricante (NombreF) VALUES ('SAAB-SCANIA');
INSERT INTO Fabricante (NombreF) VALUES ('BEECH');
INSERT INTO Fabricante (NombreF) VALUES ('SIKORSKY');
INSERT INTO Fabricante (NombreF) VALUES ('GULFSTREAM AEROSPACE');
INSERT INTO Fabricante (NombreF) VALUES ('AEROSPATIALE');
INSERT INTO Fabricante (NombreF) VALUES ('PIPER');
INSERT INTO Fabricante (NombreF) VALUES ('AGUSTA SPA');
INSERT INTO Fabricante (NombreF) VALUES ('AERO COMMANDER');
INSERT INTO Fabricante (NombreF) VALUES ('PAIR MIKE E');
INSERT INTO Fabricante (NombreF) VALUES ('AVIAT AIRCRAFT INC');
INSERT INTO Fabricante (NombreF) VALUES ('RAVEN');
INSERT INTO Fabricante (NombreF) VALUES ('DEHAVILLAND');
INSERT INTO Fabricante (NombreF) VALUES ('WOBIG WAYNE R');
INSERT INTO Fabricante (NombreF) VALUES ('BELL');
INSERT INTO Fabricante (NombreF) VALUES ('FREDERICK CHRIS K');
INSERT INTO Fabricante (NombreF) VALUES ('FRIEDEMANN JON');
INSERT INTO Fabricante (NombreF) VALUES ('STINNETT RON');
INSERT INTO Fabricante (NombreF) VALUES ('HELIO');
INSERT INTO Fabricante (NombreF) VALUES ('LEBLANC GLENN T');
INSERT INTO Fabricante (NombreF) VALUES ('MARZ BARRY');
INSERT INTO Fabricante (NombreF) VALUES ('MORSE GEORGE JR');
INSERT INTO Fabricante (NombreF) VALUES ('AEROSPATIALE/ALENIA');
INSERT INTO Fabricante (NombreF) VALUES ('BAUMAN RANDY');
INSERT INTO Fabricante (NombreF) VALUES ('DIAMOND AIRCRAFT IND INC');
INSERT INTO Fabricante (NombreF) VALUES ('BOEING OF CANADA LTD');
INSERT INTO Fabricante (NombreF) VALUES ('MCDONNELL DOUGLAS CORPORATION');
INSERT INTO Fabricante (NombreF) VALUES ('MCDONNELL DOUGLAS AIRCRAFT CO');
INSERT INTO Fabricante (NombreF) VALUES ('COBB INTL/DBA ROTORWAY INTL IN');
INSERT INTO Fabricante (NombreF) VALUES ('AERONCA');
INSERT INTO Fabricante (NombreF) VALUES ('MAULE');
