/* Generated By:JavaCC: Do not edit this line. clikeConstants.java */
package traductor;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface clikeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int tBOOL = 3;
  /** RegularExpression Id. */
  int tCHAR = 4;
  /** RegularExpression Id. */
  int tINT = 5;
  /** RegularExpression Id. */
  int tVOID = 6;
  /** RegularExpression Id. */
  int tIF = 7;
  /** RegularExpression Id. */
  int tELSE = 8;
  /** RegularExpression Id. */
  int tWHILE = 9;
  /** RegularExpression Id. */
  int tRETURN = 10;
  /** RegularExpression Id. */
  int tPAREN_INI = 11;
  /** RegularExpression Id. */
  int tPAREN_FIN = 12;
  /** RegularExpression Id. */
  int tLLAVE_INI = 13;
  /** RegularExpression Id. */
  int tLLAVE_FIN = 14;
  /** RegularExpression Id. */
  int tCORCH_INI = 15;
  /** RegularExpression Id. */
  int tCORCH_FIN = 16;
  /** RegularExpression Id. */
  int tCOMA = 17;
  /** RegularExpression Id. */
  int tPUNTO_COMA = 18;
  /** RegularExpression Id. */
  int tASIGNAR = 19;
  /** RegularExpression Id. */
  int tSUMA = 20;
  /** RegularExpression Id. */
  int tRESTA = 21;
  /** RegularExpression Id. */
  int tMULTI = 22;
  /** RegularExpression Id. */
  int tDIV = 23;
  /** RegularExpression Id. */
  int tMODULO = 24;
  /** RegularExpression Id. */
  int tMAYOR = 25;
  /** RegularExpression Id. */
  int tMENOR = 26;
  /** RegularExpression Id. */
  int tMAYOR_IGUAL = 27;
  /** RegularExpression Id. */
  int tMENOR_IGUAL = 28;
  /** RegularExpression Id. */
  int tIGUAL = 29;
  /** RegularExpression Id. */
  int tDISTINTO = 30;
  /** RegularExpression Id. */
  int tAND = 31;
  /** RegularExpression Id. */
  int tOR = 32;
  /** RegularExpression Id. */
  int tNOT = 33;
  /** RegularExpression Id. */
  int tAMPERSAND = 34;
  /** RegularExpression Id. */
  int tPRINT = 35;
  /** RegularExpression Id. */
  int tPRINT_LN = 36;
  /** RegularExpression Id. */
  int tREAD = 37;
  /** RegularExpression Id. */
  int tREAD_LN = 38;
  /** RegularExpression Id. */
  int tINT2CHAR = 39;
  /** RegularExpression Id. */
  int tCHAR2INT = 40;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 41;
  /** RegularExpression Id. */
  int tCONST_CHAR = 42;
  /** RegularExpression Id. */
  int tCONST_STRING = 43;
  /** RegularExpression Id. */
  int tCONST_NUM = 44;
  /** RegularExpression Id. */
  int tTRUE = 45;
  /** RegularExpression Id. */
  int tFALSE = 46;
  /** RegularExpression Id. */
  int tCOMENTARIO = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LETTER>",
    "<DIGIT>",
    "\"bool\"",
    "\"char\"",
    "\"int\"",
    "\"void\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"&\"",
    "\"print\"",
    "\"print_ln\"",
    "\"read\"",
    "\"read_ln\"",
    "\"int2char\"",
    "\"char2int\"",
    "<tIDENTIFICADOR>",
    "<tCONST_CHAR>",
    "<tCONST_STRING>",
    "<tCONST_NUM>",
    "\"true\"",
    "\"false\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<tCOMENTARIO>",
  };

}
